TRUNCATE comment CASCADE;
TRUNCATE exercise CASCADE;
TRUNCATE exercise_tag CASCADE;
TRUNCATE exoluser CASCADE;
TRUNCATE solution CASCADE;
TRUNCATE tag CASCADE;
TRUNCATE track CASCADE;
TRUNCATE vote CASCADE;

